- name: Create directories and clone repositories to their proper location
  ansible.builtin.import_tasks: clone.yml

- name: Deploy install and configure nginx
  ansible.builtin.import_tasks: nginx.yml
