---
- name: Ensure user hackfest is present
  ansible.builtin.user:
    name: hackfest
    password: "{{ hackfest_pw }}"
    shell: /bin/ksh
    groups: wheel
    append: true
    state: present
    create_home: true

- name: Deploy SSH Bitbucket Private Key
  ansible.builtin.copy:
    content: "{{ hackfest_bitbucket_key }}"
    dest: "/home/hackfest/.ssh/{{ hackfest_keyname }}"
    owner: "hackfest"
    group: "hackfest"
    mode: '0600'

- name: Deploy SSH Bitbucket Public Key
  ansible.builtin.copy:
    content: "{{ hackfest_bitbucket_key_pub }}"
    dest: "/home/hackfest/.ssh/{{ hackfest_keyname }}.pub"
    owner: "hackfest"
    group: "hackfest"
    mode: '0644'
