- name: Load list of sites
  ansible.builtin.include_vars:
    file: vars/sites.yml

- name: Clone each site in proper location
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    key_file: "/home/hackfest/.ssh/{{ hackfest_keyname }}"
    accept_hostkey: true
  become: true
  become_user: hackfest
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"
