- name: Set timezone
  ansible.builtin.file:
    src: /usr/share/zoneinfo/America/Montreal
    dest: /etc/localtime
    state: link
    force: true

- name: Ensure packages are present
  community.general.openbsd_pkg:
    name:
      - git
      - slurm
    state: present

- name: Ensure user hackfest is present
  user:
    name: hackfest
    password: "{{ hackfest_pw }}"
    shell: /bin/ksh
    groups: wheel
    append: true
    state: present
    create_home: yes

