---
- name: Set timezone
  ansible.builtin.file:
    src: /usr/share/zoneinfo/America/Montreal
    dest: /etc/localtime
    state: link
    force: true
  notify: restart ntpd

- name: Ensure packages are present
  community.general.openbsd_pkg:
    name:
      - git
      - slurm
    state: present

- name: Ensure root alias is set to root@mantor.org
  ansible.builtin.lineinfile:
    path: /etc/mail/aliases
    regexp: '^root:'
    line: 'root: root@mantor.org'
  notify: update aliases
